config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get 'about', to: "static_pages#about"
  get 'contact', to: "static_pages#contact"
  get 'help', to: "static_pages#help"
  get 'signup', to: 'users#new'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  # adds all actions for Users
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # callback gets called before saving user to db
  # before_save { self.email = email.downcase }
  # same as above
  before_save { email.downcase! }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, 
                    format: { with: VALID_EMAIL_REGEX },
                    # does not guarantee uniqueness at db level
                    uniqueness: true

  # adds the following functionality:
    # - ability to save hashed password_digest attribute
    # - a pair of virtual attributes (password + password_confirmation)
    # - authenticate method that returns the user when correct
  has_secure_password
  # has_secure_password includes a presence validation but it applies only
  # to records with empty passwords which would allow a user to create an 
  # invalid password like "       "
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session # prevents session fixation attack which tricks usr into using a session id known to the attacker, allowing the attacker to share the seeeession. This resets the session and clears the id before logging the user in
      log_in user
      redirect_to user
    else
      # using flash.now will cause message to disappear after a new request
      flash.now[:danger] = "Invalid email/password combination"
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def home
  end

  def help
  end

  def login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new(params[:user])
  end

  def show
    @user = User.find(params[:id])
    # debugger
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # method that displays a temporary messagee
      flash[:success] = "Welcome to Blog 24!"
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

    def user_params
      # require :user attribute and only permit the following attributes
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # returns the full title on a per-page basis
  def full_title(page_title = '')
    base_title = "Blog 24"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    # places a temp cookie on the browser containing
    # encrypted user.id expires when browser is closed
    session[:user_id] = user.id
  end

  # returns the current logged-in user
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # returns true if user is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar rounded-full")
  end
end

app/views/layouts/_footer.html.erb
<footer class="bg-fuchsia-950 text-stone-100 p-4">
  <div class="container flex justify-between mx-auto">
    <small>Blog 24 brought to you with ❤️</small>
    <nav>
      <ul class="flex gap-2">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
        <li><%= link_to 'News', '#' %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="fixed w-full bg-fuchsia-200 p-4 top-0 z-10">
  <div class="container flex justify-between mx-auto">
    <%= link_to "Blog 24" , root_path, id: "logo" %>
      <nav>
        <div class="navbar-header">
          <button id="hamburger" type="button" class="navbar-toggle collapsed flex flex-col gap-1 ml-auto">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar w-8 h-1 bg-slate-900 block"></span>
            <span class="icon-bar w-8 h-1 bg-slate-900 block"></span>
            <span class="icon-bar w-8 h-1 bg-slate-900 block"></span>
          </button>
        </div>
        <ul class="list-none mt-2 flex-col collapse md:flex-row items-start md:items-center gap-4" id="navbar-menu">
          <li>
            <%= link_to "Home" , root_path %>
          </li>
          <li>
            <%= link_to "Help" , help_path %>
          </li>
          <% if logged_in? %>
            <li><%= link_to "Users", "#" %></li>
            <div class="relative inline-block text-left">
              <div>
                <button type="button" class="inline-flex w-full justify-center items-center gap-x-1.5 rounded-lg p-3 bg-transparent px-3 py-2 text-sm font-semibold text-gray-900 hover:bg-gray-50" id="menu-button">
                  Account &#9660;
                </button>
              </div>
              <div class="dropdown-menu absolute right-0 z-10 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" tabindex="-1" id="dropdown-menu">
                <div class="py-1" role="none">
                  <li class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0"><%= link_to "Profile" , current_user %></li>
                  <li class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1"
                    id="menu-item-1"><%= link_to "Settings" , "#" %></li>
                  <li class="divider h-1 w-full bg-stone-600"></li>
                  <li class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-2">
                    <%= link_to "Log out", logout_path, data: { "turbo-method": :delete } %>
                  </li>
                </div>
              </div>
            </div>
          <% else %>
            <li><%= link_to "Login" , login_path %></li>
          <% end %>
        </ul>
      </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= full_title(yield(:title)) %>
    </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-stone-100">
    <%= render 'layouts/header' %>
    <main class="container mx-auto pt-28 pb-20 min-h-[calc(100vh-3.5rem)] px-5">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type} absolute translate-x-[-50%] left-2/4 top-6") %>
        <% end %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div>
    <div class="alert alert-danger mb-2">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul class="px-6 py-4">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About" ) %>
<h1>About Blog 24</h1>
<p>E cielo e terra si mostrò qual era:</p>

<p>la terra ansante, livida, in sussulto;</p>

<p>il cielo ingombro, tragico, disfatto:</p>

<p>bianca bianca nel tacito tumulto</p>

<p>una casa apparì sparì d'un tratto;</p>

<p>come un occhio, che, largo, esterrefatto,</p>

<p>s'aprì si chiuse, nella notte nera.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact" ) %>
<h1>Contact</h1>
<p>Contact us here shortly for more exciting news.</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help" ) %>
<h1>Help</h1>
<p>Get help on various things here.</p>

app/views/static_pages/home.html.erb
<h1>Welcome to Blog 24 ❤️</h1>
<p>This is the home page for a very interesting blog. Stay tuned for more!</p>
<p>Sign up for our newsletter to stay up to date on all the interesting things!</p>
<%= link_to 'Sign up now!' , signup_path , class: 'btn-primary mx-auto mt-6 block max-w-fit' %>

<%= link_to image_tag('https://images.unsplash.com/photo-1697933828774-7f8c651da79f?q=80&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', alt: "Sunset", class: 'w-9/12 ml-auto mt-8'), 'https://www.google.com/' %>

<div class="h-16"></div>
<p>Sull'orlo dell'oceano, dove il cielo si tuffa,</p>
<p>Un mondo di meraviglia si apre, senza grida o zuffa.</p>
<p>Danzano le onde al ritmo del vento,</p>
<p>In un eterno abbraccio, un dolce fermento.</p>
<div class="h-4"></div>
<p>Il mare, con la sua vastità senza fine,</p>
<p>Scintilla d'incanto, come gemma divine.</p>
<p>Le creature marine, in danza sotto il blu,</p>
<p>Raccontano segreti, antichi come l'azzurro.</p>
<div class="h-4"></div>
<p>Sotto il sole, la sabbia dorata si scalda,</p>
<p>Un incanto di colori, dove la mente si calma.</p>
<p>I gabbiani danzano nell'aria serena,</p>
<p>Tra le risacche e le rocce, la natura è regina.</p>
<div class="h-4"></div>
<p>In questo regno di meraviglia e splendore,</p>
<p>Ogni onda, ogni granello di sabbia è un amore.</p>
<p>L'oceano canta una canzone senza fine,</p>
<p>E nell'abbraccio della natura, il cuore trova il suo confine.</p>
<div class="h-4"></div>
<p>Così inebriati dalla bellezza del mondo,</p>
<p>Ci avventuriamo, come viandanti senza tondo.</p>
<p>Nel mistero e nell'ammirazione, ci immergiamo,</p>
<p>Nell'oceano infinito, i nostri sogni piantiamo.</p>

app/views/static_pages/login.html.erb
<% provide(:title, "Login" ) %>

<button class="btn-primary mx-auto mt-6 block max-w-fit">Login</button>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<div class="max-w-md mx-auto">
  <%= form_with(model: @user) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="flex flex-col gap-y-1">
      <div class="grid grid-cols-2 gap-2 items-center">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'rounded-md w-full form-control' %>
      </div>
      <div class="grid grid-cols-2 gap-2 items-center">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'rounded-md w-full form-control' %>
      </div>
      <div class="grid grid-cols-2 gap-2 items-center">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'rounded-md w-full form-control' %>
      </div>
      <div class="grid grid-cols-2 gap-2 items-center">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'rounded-md w-full form-control' %>
      </div>
      <%= f.submit "Create my account", class: "btn-primary mt-4 self-center" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="flex">
  <aside class="flex gap-4 items-center">
    <%= gravatar_for @user %>
    <h1><%= @user.name %></h1>
  </aside>
</div>

<!-- 
  Debugging options:
  <%= simple_format @user.to_yaml %>
  <%= @user.inspect %> 
-->